spring.application.name=backend



spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# le port des requettes axios
server.port=8586
spring.datasource.url=jdbc:mariadb://localhost:3306/fullstack
spring.datasource.username=root
spring.datasource.password=
#pour prod mettre update
spring.jpa.hibernate.ddl-auto=create-drop


#inserer données
#pour prod pas mettre ca
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always